[build]
target-dir = "target"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
    "-C", "target-cpu=native",
]

[profile.release-lto]
inherits = "release"
lto = "fat"
codegen-units = 1