# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: forzium.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "forzium.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rforzium.proto\x12\x07\x66orzium"\x1e\n\x0bJsonPayload\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x32\x7f\n\x07\x46orzium\x12\x35\n\x07\x43ompute\x12\x14.forzium.JsonPayload\x1a\x14.forzium.JsonPayload\x12=\n\rStreamCompute\x12\x14.forzium.JsonPayload\x1a\x14.forzium.JsonPayload0\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "forzium_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_JSONPAYLOAD"]._serialized_start = 26
    _globals["_JSONPAYLOAD"]._serialized_end = 56
    _globals["_FORZIUM"]._serialized_start = 58
    _globals["_FORZIUM"]._serialized_end = 185
# @@protoc_insertion_point(module_scope)
