repos:
  # 1. All languages
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-added-large-files

  # 2. Python
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--max-line-length=78"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        additional_dependencies: [pbr]
        args: ["-x", "tests"]

  # 3. Rust
  - repo: local
    hooks:
      - id: rustfmt
        name: RustFmt ― cargo fmt
        entry: cargo fmt --manifest-path core/rust_engine/Cargo.toml --all -- --check
        language: system
        files: \.rs$
        pass_filenames: false
      - id: clippy
        name: Clippy ― cargo clippy
        entry: cargo clippy --manifest-path core/rust_engine/Cargo.toml --all-targets -- -D warnings
        language: system
        files: \.rs$
        pass_filenames: false
      - id: cargo-check
        name: Cargo Check ― cargo check
        entry: cargo audit -f core/rust_engine/Cargo.lock
        language: system
        files: \.rs$
        pass_filenames: false
      - id: cargo-check
        name: Cargo Check ― cargo check
        entry: cargo check --manifest-path core/rust_engine/Cargo.toml --all-targets
        language: system
        files: \.rs$
        pass_filenames: false
