repos:
  # 1. All languages
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-added-large-files

  # 2. Python
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: ["--max-line-length=88"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --no-strict-optional]
        additional_dependencies: [types-all]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.0
    hooks:
      - id: bandit
        additional_dependencies: [pbr]
        args: ["-x", "tests"]

  # 3. Rust
  - repo: local
    hooks:
      - id: rustfmt
        name: RustFmt ― cargo fmt
        entry: cargo fmt --manifest-path core/rust_engine/Cargo.toml --all -- --check
        language: system
        files: \.rs$
        pass_filenames: false
      - id: clippy
        name: Clippy ― cargo clippy
        entry: cargo clippy --manifest-path core/rust_engine/Cargo.toml --all-targets -- -D warnings
        language: system
        files: \.rs$
        pass_filenames: false
      - id: cargo-audit
        name: Cargo Audit ― cargo audit
        entry: cargo audit -f core/rust_engine/Cargo.lock
        language: system
        files: \.rs$
        pass_filenames: false
      - id: cargo-check
        name: Cargo Check ― cargo check
        entry: cargo check --manifest-path core/rust_engine/Cargo.toml --all-targets
        language: system
        files: \.rs$
        pass_filenames: false
