# Core constants
MAX_BUFFER_SIZE = 10_485_760  # 10MB
DEFAULT_TIMEOUT = 30.0  # seconds
MAX_PATH_LENGTH = 2048
MAX_HEADER_SIZE = 8192

__all__ = ['MAX_BUFFER_SIZE', 'DEFAULT_TIMEOUT', 'MAX_PATH_LENGTH', 'MAX_HEADER_SIZE']
