MAX_BUFFER_SIZE = 10_485_760
DEFAULT_TIMEOUT = 30.0
MIN_PYTHON_VERSION = (3, 8)
MAX_PYTHON_VERSION = (3, 14)

__all__ = ['MAX_BUFFER_SIZE', 'DEFAULT_TIMEOUT', 'MIN_PYTHON_VERSION', 'MAX_PYTHON_VERSION']