apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: forzium
spec:
  template:
    spec:
      containers:
        - image: gcr.io/your-project/forzium:latest
          ports:
            - containerPort: 8000