receivers:
  otlp:
    protocols:
      grpc:
      http:
  prometheus:
    config:
      scrape_configs:
        - job_name: forzium-api
          static_configs:
            - targets: ["api:8000"]
          metrics_path: /metrics
processors:
  batch:
    send_batch_size: 4096
    timeout: 5s
exporters:
  logging:
    loglevel: warn
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  prometheus:
    endpoint: 0.0.0.0:9464
    const_labels:
      service: forzium-api
service:
  telemetry:
    logs:
      level: warn
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger, logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]