[package]
name = "project-core"
version = "0.1.0"
edition = "2018"
rust-version = "1.75.0"

# This is the main entry for the project metadata
authors = ["pavanepour.k <pavanepour@outlook.com>"]
license = "MIT"
description = "Core business logic for the project"

[dependencies]
# Standard Rust dependencies
serde = { version = "1.0", features = ["derive"] }   # For serialization/deserialization
serde_json = "1.0"  # JSON support via serde
tokio = { version = "1", features = ["full"] }  # Optional: For async Rust

# Optional: For Rust testing
criterion = "0.3.6"  # For performance benchmarking
# Unit test dependencies
thiserror = "1.0.69"  # For structured error handling

[dev-dependencies]
# Development-only dependencies

[build-dependencies]
# Build dependencies, if needed (e.g., for compiling native extensions)
maturin = "0.12"  # Used for building Python bindings from Rust

[lints.rust]
unsafe_code = "deny"
missing_docs = "warn"

[lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"
cargo = "warn"

[features]
# Optional features (e.g., for optional compilation)
default = []
