name: PYTHON

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: SET UP PYTHON
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: INSTALL POETRY
        uses: snok/install-poetry@v1
        with:
          version: 1.7.0
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: LOAD CACHED VENV
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: INSTALL DEPENDENCIES
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: |
          cd python
          poetry install --no-interaction --no-root

      - name: RUN TESTS
        run: |
          cd python
          poetry run pytest -xvs

      - name: CHECK COVERAGE
        run: |
          cd python
          poetry run pytest --cov=src --cov-fail-under=90

      - name: RUN LINTERS
        run: |
          cd python
          poetry run ruff check src tests
          poetry run mypy src
          poetry run black --check src tests
